-- ========================================================
-- OFFSTAGE SESSIONS — SUPABASE DATABASE SCHEMA & MIGRATION
-- Copy and run this script in the Supabase SQL Editor
-- ========================================================

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ========================================================
-- 1. TABLE: SHOWS (Events, Performances, Tours)
-- ========================================================
CREATE TABLE IF NOT EXISTS public.shows (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name TEXT NOT NULL,
    subtitle TEXT,
    date_code TEXT NOT NULL,                -- e.g. "07.25"
    date_formatted TEXT NOT NULL,           -- e.g. "Fri<br>Jul 25"
    event_date TIMESTAMPTZ,                 -- Exact ISO timestamp for chronologic sorting
    venue TEXT NOT NULL,                    -- e.g. "Sound Garden / Arepi, Baltimore"
    time TEXT NOT NULL,                     -- e.g. "4:00 PM — 9:00 PM"
    poster_url TEXT NOT NULL,               -- Cloudinary / local webp URL
    tags TEXT[] DEFAULT ARRAY['House']::TEXT[], -- e.g. ['House', 'Techno']
    featured BOOLEAN DEFAULT FALSE,
    month TEXT NOT NULL,                    -- e.g. "July 2026"
    ticket_url TEXT,                        -- Direct Ticket / Posh.vip URL
    posh_url TEXT,                          -- Posh.vip Ticket / Event URL
    status TEXT DEFAULT 'upcoming' CHECK (status IN ('upcoming', 'past', 'cancelled')),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Index for querying shows by status, featured, and event_date
CREATE INDEX IF NOT EXISTS idx_shows_status_event_date ON public.shows(status, event_date);

-- ============================================================================
-- 2. MEDIA ARCHIVES TABLE
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.media_archives (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,                     -- e.g. "JACKIE HOLLANDER 6.13"
    date TEXT NOT NULL,                     -- e.g. "JUNE 13, 2026 · SOUNDSTAGE"
    thumbnail_url TEXT NOT NULL,            -- Cloudinary thumbnail
    image_url TEXT,                         -- Cloudinary full-size preview
    facebook_url TEXT NOT NULL,             -- Destination Facebook photo album URL
    category TEXT DEFAULT 'photo' CHECK (category IN ('photo', 'video', 'highlight', 'mix', 'gallery')),
    display_order INT DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================================
-- 3. CONTACT INQUIRIES TABLE
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.contact_inquiries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT,
    email TEXT,
    subject TEXT NOT NULL,
    category TEXT DEFAULT 'General',
    message TEXT NOT NULL,
    status TEXT DEFAULT 'unread' CHECK (status IN ('unread', 'read', 'archived', 'replied')),
    ip_address TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================================
-- 4. PAGE VIEWS & SITE TRAFFIC ANALYTICS TABLE
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.page_views (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    page_path TEXT NOT NULL,
    referrer TEXT,
    user_agent TEXT,
    device_type TEXT DEFAULT 'desktop',
    browser TEXT,
    os TEXT,
    ip_hash TEXT,
    country TEXT DEFAULT 'Unknown',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_page_views_created_at ON public.page_views(created_at);
CREATE INDEX IF NOT EXISTS idx_page_views_page_path ON public.page_views(page_path);

-- ============================================================================
-- 5. SITE SETTINGS & CONFIGURATION TABLE (Social Media & Site Metadata)
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.site_settings (
    key TEXT PRIMARY KEY,
    value JSONB NOT NULL,
    description TEXT,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================================
-- 6. ROW-LEVEL SECURITY (RLS) POLICIES
-- ============================================================================
ALTER TABLE public.shows ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.media_archives ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.contact_inquiries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.page_views ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.site_settings ENABLE ROW LEVEL SECURITY;

-- Anonymous public read access for shows, media archives, and site settings
CREATE POLICY "Public shows are viewable by everyone" 
ON public.shows FOR SELECT USING (true);

CREATE POLICY "Public media is viewable by everyone" 
ON public.media_archives FOR SELECT USING (true);

CREATE POLICY "Public settings are viewable by everyone" 
ON public.site_settings FOR SELECT USING (true);

-- Anonymous users can insert contact inquiries
CREATE POLICY "Public can submit contact inquiries" 
ON public.contact_inquiries FOR INSERT WITH CHECK (true);

-- Anonymous users can record page views for analytics
CREATE POLICY "Public can record page views" 
ON public.page_views FOR INSERT WITH CHECK (true);

-- Service role full access for backend admin operations
CREATE POLICY "Admin full access on shows" 
ON public.shows FOR ALL 
USING (auth.jwt() ->> 'role' = 'service_role' OR auth.role() = 'service_role');

CREATE POLICY "Admin full access on media" 
ON public.media_archives FOR ALL 
USING (auth.jwt() ->> 'role' = 'service_role' OR auth.role() = 'service_role');

CREATE POLICY "Admin full access on inquiries" 
ON public.contact_inquiries FOR ALL 
USING (auth.jwt() ->> 'role' = 'service_role' OR auth.role() = 'service_role');

CREATE POLICY "Admin full access on page_views" 
ON public.page_views FOR ALL 
USING (auth.jwt() ->> 'role' = 'service_role' OR auth.role() = 'service_role');

CREATE POLICY "Admin full access on site_settings" 
ON public.site_settings FOR ALL 
USING (auth.jwt() ->> 'role' = 'service_role' OR auth.role() = 'service_role');

-- ============================================================================
-- 7. INITIAL SEED DATA
-- ============================================================================
-- Seed: Shows & Tour Dates
INSERT INTO public.shows (
    name, subtitle, date_code, date_formatted, event_date, venue, time, poster_url, tags, featured, month, ticket_url, posh_url, status
) VALUES
(
    'TO BE HONEST',
    NULL,
    '07.25',
    'Fri<br>Jul 25',
    '2026-07-25T16:00:00Z',
    'Sound Garden / Arepi, Baltimore',
    '4:00 PM — 9:00 PM',
    '/image/tobehonest_web.webp',
    ARRAY['House', 'Techno'],
    TRUE,
    'July 2026',
    'https://posh.vip/e/to-be-honest-baltimore',
    'https://posh.vip/e/to-be-honest-baltimore',
    'upcoming'
),
(
    'NIGHT SWIM',
    'OFFSTAGE 3 YEARS ANNIVERSARY',
    '08.14',
    'Fri<br>Aug 14',
    '2026-08-14T18:00:00Z',
    'Raw & Refined, Baltimore',
    '6:00 PM — 12:00 AM',
    '/image/nightswim_web.webp',
    ARRAY['House', 'Techno'],
    FALSE,
    'August 2026',
    'https://posh.vip/e/night-swim-3-years',
    'https://posh.vip/e/night-swim-3-years',
    'upcoming'
),
(
    'GROW GARDEN',
    'OFFSTAGE 3 YEARS ANNIVERSARY',
    '08.15',
    'Sat<br>Aug 15',
    '2026-08-15T16:00:00Z',
    'Sound Garden / Arepi, Baltimore',
    '4:00 PM — 9:00 PM',
    '/image/growgarden_web.webp',
    ARRAY['House'],
    FALSE,
    'August 2026',
    'https://posh.vip/e/grow-garden-open-air',
    'https://posh.vip/e/grow-garden-open-air',
    'upcoming'
),
(
    'LATE CHECKOUT',
    NULL,
    '08.21',
    'Thu<br>Aug 21',
    '2026-08-21T19:00:00Z',
    'Waterfront Hotel, Baltimore',
    '7:00 PM — 2:00 AM',
    '/image/latecheckout_web.webp',
    ARRAY['House', 'Bass'],
    FALSE,
    'August 2026',
    'https://posh.vip/e/late-checkout-baltimore',
    'https://posh.vip/e/late-checkout-baltimore',
    'upcoming'
),
(
    'JACKIE HOLLANDER',
    NULL,
    '09.12',
    'Sat<br>Sep 12',
    '2026-09-12T21:00:00Z',
    'Baltimore Soundstage, Baltimore',
    '9:00 PM — 2:00 AM',
    '/image/jackie_web.webp',
    ARRAY['House', 'Techno'],
    FALSE,
    'September 2026',
    'https://posh.vip/e/jackie-hollander',
    'https://posh.vip/e/jackie-hollander',
    'upcoming'
),
(
    'SHIP WREK',
    NULL,
    '10.03',
    'Sat<br>Oct 03',
    '2026-10-03T20:00:00Z',
    'Power Plant Live, Baltimore',
    '8:00 PM — 2:00 AM',
    '/image/shipwreck_web.webp',
    ARRAY['Bass', 'House'],
    FALSE,
    'October 2026',
    'https://posh.vip/e/ship-wrek-live',
    'https://posh.vip/e/ship-wrek-live',
    'upcoming'
)
ON CONFLICT DO NOTHING;

-- Seed: Media Archives (linked to Facebook photo galleries)
INSERT INTO public.media_archives (
    name, date, thumbnail_url, image_url, facebook_url, category, display_order
) VALUES
(
    'JACKIE HOLLANDER 6.13',
    'JUNE 13, 2026 · SOUNDSTAGE',
    '/image/jackie_web.webp',
    '/image/jackie_web.webp',
    'https://www.facebook.com/offstagesessions',
    'photo',
    1
),
(
    'HONEYLUV 5.02',
    'MAY 2, 2026 · WAREHOUSE 8',
    '/image/honey_web.webp',
    '/image/honey_web.webp',
    'https://www.facebook.com/offstagesessions',
    'photo',
    2
),
(
    'SHIP WREK 4.10',
    'APRIL 10, 2026 · POWER PLANT',
    '/image/shipwreck_web.webp',
    '/image/shipwreck_web.webp',
    'https://www.facebook.com/offstagesessions',
    'photo',
    3
),
(
    'TO BE HONEST 5.09',
    'MAY 9, 2026 · SOUND GARDEN',
    '/image/tobehonest_web.webp',
    '/image/tobehonest_web.webp',
    'https://www.facebook.com/offstagesessions',
    'photo',
    4
),
(
    'NIGHT SWIM 3.28',
    'MARCH 28, 2026 · THE WATERFRONT',
    '/image/nightswim_web.webp',
    '/image/nightswim_web.webp',
    'https://www.facebook.com/offstagesessions',
    'photo',
    5
),
(
    'GROW GARDEN 4.25',
    'APRIL 25, 2026 · OPEN AIR DC',
    '/image/growgarden_web.webp',
    '/image/growgarden_web.webp',
    'https://www.facebook.com/offstagesessions',
    'photo',
    6
)
ON CONFLICT DO NOTHING;

-- Seed: Default Site Settings (Social Media links)
INSERT INTO public.site_settings (key, value, description)
VALUES (
    'social_links',
    '{
        "instagram": "https://instagram.com/offstagesession",
        "tiktok": "https://www.tiktok.com/@offstagesessions",
        "facebook": "https://www.facebook.com/offstagesessions",
        "email": "offstage@offstagesessions.com",
        "spotify": "",
        "soundcloud": "",
        "youtube": ""
    }'::jsonb,
    'Social media & channel links used across the site'
)
ON CONFLICT (key) DO NOTHING;

